CREATE DATABASE IF NOT EXISTS CITY_APP;

USE CITY_APP;

DROP TABLE IF EXISTS city;

CREATE TABLE IF NOT EXISTS city (
    id int NOT NULL AUTO_INCREMENT,
    country varchar(255)
);


INSERT INTO city(country) VALUES("EGYPT");
INSERT INTO city(country) VALUES("ESTONIA");
INSERT INTO city(country) VALUES("ENGLAND");